### ISSUE TITLE
Allow incrementing patch version

### ISSUE THREAD

**Issue by iacobfred** [int128/release-typescript-action#216]
Hi, this action is great. Thanks for writing it.

I'd like to use the action more flexibly to create releases associated with patch versions, not just major/minor versions.
I've submitted a PR (https://github.com/int128/release-typescript-action/pull/215) for this but could use help testing if you would be willing.

**Comment by int128** [comment]
I added as https://github.com/int128/release-typescript-action/pull/354. Thank you for bringing up the issue!
